% DREAD — autonomic arousal model
% =================================================================
% Run this in MATLAB (Rice has a campus licence — sign in with your
% rice.edu address). It fits a model of sympathetic/parasympathetic
% balance from heart rate and heart-rate variability, then exports a
% lookup table the game interpolates at runtime.
%
%   >> autonomic_model
%
% Writes: ../src/game/arousalTable.json
%
% WHY A LOOKUP TABLE, NOT A LIVE CALL:
% The game is a static site running in a browser at 60fps. It cannot
% call MATLAB, and it must not depend on anything that can fail during
% a live demo. So the modelling happens here, once, offline, and the
% game ships the solved result. This is the standard way to get a
% MATLAB-designed controller into a realtime target and it's also the
% only honest way to claim the model is doing real work.
%
% THE MODEL:
% Heart rate alone is a poor arousal signal — a resting rate of 50 and
% a resting rate of 90 are both "calm" for their owner. What separates
% arousal from baseline is (a) the DEVIATION from that person's own
% resting rate, and (b) the collapse in beat-to-beat variability that
% accompanies sympathetic activation. Parasympathetic ("rest and
% digest") tone shows up as high HRV; sympathetic ("fight or flight")
% activation suppresses it. So we model arousal as a function of both.
%
% Baevsky's Stress Index is the established formulation of this idea
% and is what the Presage SDK exposes directly; this model is fit to
% agree with it over the plausible range, so the game can fall back to
% the table when only HR is available.

clear; clc;

%% ---- Input domain ------------------------------------------------
% Normalised HR deviation from the player's own calibrated baseline,
% in bpm. -20 (well below rest) to +45 (severe fright).
hr_delta = linspace(-20, 45, 66);

% RMSSD, root mean square of successive RR differences, in ms. This is
% the standard short-window HRV measure. ~10ms is heavily suppressed
% (high sympathetic drive), ~120ms is relaxed parasympathetic tone.
rmssd = linspace(8, 120, 57);

[HR, RM] = meshgrid(hr_delta, rmssd);

%% ---- Sympathetic activation --------------------------------------
% Rises with HR deviation above baseline, saturating — there is a
% ceiling to how frightened a reading can report. Logistic, centred at
% +14bpm which is roughly where a startle response lands.
symp_hr = 1 ./ (1 + exp(-0.18 * (HR - 14)));

% Rises as variability collapses. Inverse-exponential in RMSSD.
symp_hrv = exp(-(RM - 8) / 38);

% Combined, weighted toward HRV because variability collapse leads the
% heart-rate rise by a second or two — it is the earlier signal.
sympathetic = 0.42 * symp_hr + 0.58 * symp_hrv;

%% ---- Parasympathetic tone ----------------------------------------
% High when variability is high AND heart rate is at or below baseline.
para_hrv = 1 ./ (1 + exp(-0.055 * (RM - 55)));
para_hr  = 1 ./ (1 + exp(0.15 * (HR - 4)));
parasympathetic = 0.6 * para_hrv + 0.4 * para_hr;

%% ---- Net arousal -------------------------------------------------
% The quantity the Director actually consumes: 0 = deeply settled,
% 1 = maximally aroused. Balance of the two branches, squashed.
raw = sympathetic - 0.75 * parasympathetic;
arousal = 1 ./ (1 + exp(-3.2 * (raw - 0.1)));

%% ---- Recovery gate -----------------------------------------------
% The Director needs to know not just "is he frightened" but "has he
% come back down enough to be frightened again". Recovery requires
% variability to have returned, not just heart rate — people whose HR
% drops while HRV stays suppressed are still activated.
recovery = (para_hrv > 0.45) & (HR < 6);

%% ---- Export ------------------------------------------------------
table.hr_delta = hr_delta;
table.rmssd = rmssd;
table.arousal = round(arousal, 4);
table.recovery = double(recovery);
table.generated = datestr(now, 'yyyy-mm-dd HH:MM:SS');
table.note = 'Generated by matlab/autonomic_model.m — do not hand-edit';

json = jsonencode(table);
outfile = fullfile(fileparts(mfilename('fullpath')), '..', 'src', 'game', 'arousalTable.json');
fid = fopen(outfile, 'w');
fwrite(fid, json, 'char');
fclose(fid);

fprintf('Wrote %s\n', outfile);
fprintf('  %d x %d grid (hr_delta x rmssd)\n', numel(hr_delta), numel(rmssd));
fprintf('  arousal range %.3f .. %.3f\n', min(arousal(:)), max(arousal(:)));

%% ---- Plots (for the demo video's technical section) --------------
figure('Name', 'DREAD autonomic model', 'Color', 'w');

subplot(1,3,1);
surf(HR, RM, sympathetic, 'EdgeColor', 'none');
xlabel('HR delta (bpm)'); ylabel('RMSSD (ms)'); zlabel('sympathetic');
title('Sympathetic activation'); view(45, 30); colormap turbo;

subplot(1,3,2);
surf(HR, RM, parasympathetic, 'EdgeColor', 'none');
xlabel('HR delta (bpm)'); ylabel('RMSSD (ms)'); zlabel('parasympathetic');
title('Parasympathetic tone'); view(45, 30);

subplot(1,3,3);
surf(HR, RM, arousal, 'EdgeColor', 'none');
xlabel('HR delta (bpm)'); ylabel('RMSSD (ms)'); zlabel('arousal');
title('Net arousal (what the game uses)'); view(45, 30);

saveas(gcf, fullfile(fileparts(mfilename('fullpath')), 'autonomic_model.png'));
fprintf('Saved surface plots to matlab/autonomic_model.png\n');
